### ISSUE TITLE
Project 4 Pitch

### ISSUE THREAD

**Issue by htylerbrooks** [ga-dc/wdidc5_project4#23]
I was thinking about making an JS based web arcade with games (at least two, stretch three). The games would be like hangman and tic-tac-toe or something to that nature.

**Comment by adambray** [comment]
Hey Tyler,

I think this is a good idea! I'd have a clear plan for which games you'd implement, and in which order. Aim to do the easiest one first, as a warm up, and so that you definitely have something to demo. Then try to add more in increasing difficulty.

I'd also encourage you to explore using WebSockets, but perhaps only after you've got at least one game implemented and working.

-Adam
