### ISSUE TITLE
Project 4 Pitch from Don McLamb and Nic Small

### ISSUE THREAD

**Issue by SmallNic** [ga-dc/wdidc5_project4#25]
With the shrinking of the print industry, writers are finding it more and more difficult to not only publish their work, but even find readers with which to share it. 

We believe there is still an audience hungry for new and inventive fiction and non-fiction that doesn’t necessarily travel through the traditional print routes. 

Writer’s Hub (our app) satisfies both sides: it provides writers with a venue for sharing their stories with an audience, and it allows readers to review those stories while providing valuable feedback.

**Comment by jshawl** [comment]
:+1: Awesome idea! It would be great to see users uploading writing ideas, and writers can write based on what the readers want to read.

Also, you could try implementing a real-time chat or messaging feature. Please let me know if you'd like more feedback or direction on this project - otherwise good to go!

**Comment by SmallNic** [comment]
Thanks so much Jesse. Really appreciate your enthusiasm. We have a ton of ideas and are continually narrowing it down to an achievable MVP. A messaging feature would be awesome though. I like the idea of prompts for writers too. Exciting!
