### ISSUE TITLE
route error

### ISSUE THREAD

**Issue by janicemin** [ga-dc/wdidc5_project4#80]
![screen shot 2015-06-01 at 6 15 07 pm](https://cloud.githubusercontent.com/assets/11448897/7924556/37c31d46-088a-11e5-9e94-f4b4d0f67559.png)

not sure how to fix this error? thought i had all my routes set up properly...
https://github.com/janicemin/breakupbud

**Comment by RobertAKARobin** [comment]
What are you doing when this occurs?

**Comment by janicemin** [comment]
just trying to refresh the browser on localhost:3000

**Comment by RobertAKARobin** [comment]
OK

**Comment by RobertAKARobin** [comment]
I think the problem here is that you overwrote the default Users controller provided by Devise. Check this out:

https://github.com/plataformatec/devise#configuring-controllers

I'd suggest saving your app and starting a new one (_NOT_ deleting your current app), and this time leaving Users alone and instead creating a model called Profile. Each Profile belongs to a User. You can do whatever you want to Profile since it won't muck up Devise.

A better plan might be to start a new one without using authentication at all. You could just create a model called "User" that has two columns, a password and a username, and save those in your database without worrying about encryption or any of that stuff.
