### ISSUE TITLE
Parameter missing when using devise

### ISSUE THREAD

**Issue by keithknox** [ga-dc/wdidc5_project4#85]
i get the following error when i go to create a new recipe:

![image](https://cloud.githubusercontent.com/assets/8493066/7937904/8a2ddaa4-0910-11e5-9446-d86e3e94b992.png)

my controller has the following setup:

![image](https://cloud.githubusercontent.com/assets/8493066/7937930/b424bfda-0910-11e5-8cb2-9ccdb89f83b0.png)

and the form i am using to create this information looks like this:

![image](https://cloud.githubusercontent.com/assets/8493066/7937958/dd7b199c-0910-11e5-8fb4-060630740eac.png)

i am not sure what i'm missing.

**Comment by RobertAKARobin** [comment]
For now, I'd say just get rid of `private def recipe_params` altogether. It'll make your app less secure, but we don't need to be concerned with security now.

**Comment by keithknox** [comment]
ok.

**Comment by jrhorn424** [comment]
I disagree. I also disagree with the idea that "we don't need to be concerned with security right now".

@keithknox, using some sort of debugger, what is the value of `current_user` on line 25 of the Recipes Controller?

**Comment by mattscilipoti** [comment]
My steps:  
- What is the error telling me?  It is stating that my params hash does not contain all of the keys that _I_ indicated were required in the `recipe_params` method (via strong_params syntax).
- This causes me to ask myself which params are required? And which params are actually being sent?

Please answer these questions.

**Comment by mattscilipoti** [comment]
FYI: In Rails 4.2, strong_params is "on" by default.  It is no longer easy to simply ignore it.  If you do not configure your params, strong_params will raise an ActiveModel::ForbiddenAttributes exception because you are using mass assignment without an explicit permit step.  

While I agree with Robin, we don't really _need_ it for a classroom app, it is a good habit to get into and I'm glad it is enforced now.  

Please review: http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters

**Comment by RobertAKARobin** [comment]
We have different opinions about priorities in programming, Keith. Remember that how you use your time on this project is up to you. Take what I and the other instructors say as suggestions, rather than "musts". The only "must" on this project is what's detailed explicitly in the rubric.
